import { headers } from '../headers.js';

/**
 * Asynchronously fetches a specific post from the API using its ID. This function makes a GET request to the
 * API's listings endpoint for a single listing, including seller and bids information for the post. It utilizes
 * custom headers generated by the `headers` function, potentially including authentication details necessary for
 * the API request. The function parses and returns the JSON response from the API if the request is successful.
 * If the request fails due to a server-side error or other HTTP issue, it throws an error with the status text
 * from the response.
 *
 * @param {string} id - The unique identifier of the post to fetch.
 * @returns {Promise<Object>} A promise that resolves to the post object fetched from the API.
 * @throws {Error} Throws an error with the response status text if the API request is not successful.
 */
export async function getPost(id) {
  const response = await fetch(
    `https://api.noroff.dev/api/v1/auction/listings/${id}?_seller=true&_bids=true`,
    {
      headers: headers(),
    },
  );
  if (response.ok) {
    return await response.json();
  }

  throw new Error(response.statusText);
}
